version: "3.4"
services:

  minio:
    image: minio/minio:RELEASE.2024-03-10T02-53-48Z
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: sh
    command: -c 'mkdir -p /data/audio-resources && minio server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      - cloud_notebook_net

  audio-service:
    build:
      context: ./audio-service
      dockerfile: Dockerfile
    image: cloud.notebook/audio-service:1
    depends_on:
      audio-db:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://audio-pstg-db:5432/audio_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_CLOUD_AWS_S3_ENDPOINT: "http://minio:9000"
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_REGION: us-east-1
    ports:
      - "8080:8080"
    networks:
      - cloud_notebook_net

  audio-db:
    image: postgres:15.5-alpine
    container_name: audio-pstg-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audio_db
    networks:
      - cloud_notebook_net

networks:
  cloud_notebook_net: